### ISSUE TITLE
Can only assertEquals

### ISSUE THREAD

**Issue by vpong** [bluebird75/luaunit#24]
If I try any other function listed in the documentation besides `assertEquals`, I get `attempt to call global 'assertX (a nil value)`.

This is probably related, but I'm running the script by using torch, as follows:
```
$ th unittest.lua
```
If I try running it with `lua unittest.lua` I get an error saying that I don't have lua installed. I found this odd, because if I type `print(_VERSION)` in the torch REPL, I get `Lua 5.1`.

**Comment by n1tehawk** [comment]
Hi vpong!

Actually, not even `assertEquals` should be there! LuaUnit 3.1 introduced a change so that assertion functions are no longer automatically exported directly to the global namespace. This is a countermeasure to reduce "namespace pollution"; and considered good programming practice in Lua (especially with newer Lua versions).

The preferred way to include LuaUnit now is to use it as a local ("module") table, and reference test functions via this table:
```lua
local lu = require("luaunit")
print(lu.assertEquals)
print(lu.assertTrue)
```
If you wish, you can still make "legacy" use of LuaUnit - but in that case you will have to set `EXPORT_ASSERT_TO_GLOBALS`:
```lua
EXPORT_ASSERT_TO_GLOBALS = true
require("luaunit")
print(assertEquals)
print(assertTrue)
```
This is documented in the README ("History"). The various _*.lua_ files included in the distribution also demonstrate usage with and without `EXPORT_ASSERT_TO_GLOBALS`. (Your specific Lua version shouldn't matter in this context.)

Regards, NiteHawk

**Comment by vpong** [comment]
Thanks for the fast response! I made the changes and it wasn't working. However, I realize that I had installed the luaunit via

```
$ luarocks install luaunit
```

I removed it with luarocks and just cloned the repo, and your suggestion worked. Is the luaunit from luarocks a different library?

**Comment by n1tehawk** [comment]
Yes, you're right there. [luarocks](http://luarocks.org:8080/modules/rjpcomputing/luaunit) points a rockspec version `2.1-1`, which in turn references the http://github.com/rjpcomputing/luaunit repository, a forked version that seems rather outdated. Since LuaUnit basically consists of a single Lua file (`luaunit.lua`), it's best to retrieve it [directly from the repo](https://github.com/bluebird75/luaunit/raw/master/luaunit.lua) if you want the latest version.

This may be somthing that @bluebird75 will have to address at some point. See also: related issue #14

Regards, NiteHawk

**Comment by bluebird75** [comment]
Le 22/12/2015 15:37, Vitchyr Pong a écrit :
>
> Thanks for the fast response! I made the changes and it wasn't
> working. However, I realize that I had installed the luaunit via
>
> |$ luarocks install luaunit |
>
> I removed it with luarocks and just cloned the repo, and your
> suggestion worked. Is the luaunit from luarocks a different library?
>

Hi, luarocks is something that I want to support indeed. one blocker was
that I am sure yet that I have full compatiility with this fork of lua
and I was verifying it before my development stopped.

But I believe we should just go ahead, upload a new luaunit package and
deal with the behavior differences if they are reported...

Cheers,

Philippe
