### ISSUE TITLE
Appveyor build is private and unnecessarily slow

### ISSUE THREAD

**Issue by n1tehawk** [bluebird75/luaunit#39]
The Appveyor CI tests at https://ci.appveyor.com/project/bluebird75/luaunit use a private configuration. It might be preferable to have an `appveyor.yml` file included in the code base instead.

The build currently pulls in the "GnuWin" package via `cinst gnuwin`. This slows down the build considerably and is **not** needed at all; the initial `cinst lua` is already sufficient to provide a functional Lua interpreter (which runs LuaUnit just fine).

The Appveyor test differs from the Travis one in that it doesn't use `run_unit_tests.sh`. This in not a real concern, as `run_functional_tests.sh` includes the unit tests. Still it might make sense to keep both setups similar.

I've been using Appveyor on LuaUnit for quite a while now, with a build matrix covering several (binary) versions of Lua and LuaJIT. You might want to check https://github.com/n1tehawk/luaunit/blob/nitehawk/appveyor.yml and https://github.com/n1tehawk/luaunit/blob/nitehawk/.appveyor/install-lua.cmd for some ideas. (See https://ci.appveyor.com/project/n1tehawk/luaunit for actual results.)

Regards, NiteHawk

**Comment by bluebird75** [comment]
AppVeyor was initially just an experiment, that's why it was private but it should be moved to appveyor.yml indeed.

The reason it is pulling the GnuWin package is that I wanted to have the functional tests run diff on Windows. As you know, diff is not avail. by default on Windows and functional tests do rely on the avail. of diff. Last time I tried though, there was some line ending problems generating loads of diff where actually the build was fine. Withoug diff, the functional tests make less sense.

I do run functional tests on my windows, but with a cygwin diff. I did not have time to investigate the root cause for the difference.

**Comment by bluebird75** [comment]
I did not get your point about run_unit_tests.sh and run_functional_tests.sh : your appveyor is executing both the .lua versions of these files, just like your travis file.

**Comment by n1tehawk** [comment]
>I did not get your point about run_unit_tests.sh and run_functional_tests.sh : your appveyor is executing both the .lua versions of these files, just like your travis file.

I'm sorry. I got lost in the Appveyor output of your version, and failed to notice that `run_unit_tests.sh` **is** in fact executed (before GnuWin gets pulled in) - I wrongly thought is was missing. So this point is moot.

Regards, NiteHawk

**Comment by n1tehawk** [comment]
>The reason it is pulling the GnuWin package is that I wanted to have the functional tests run diff on Windows. As you know, diff is not avail. by default on Windows and functional tests do rely on the avail. of diff. Last time I tried though, there was some line ending problems generating loads of diff where actually the build was fine. Withoug diff, the functional tests make less sense.

>I do run functional tests on my windows, but with a cygwin diff. I did not have time to investigate the root cause for the difference.

I see. As Appveyor keeps evolving, it's quite possible that this was in fact an issue when you initially created your build config there. Meanwhile they seem to provide a more suitable environment by default (https://www.appveyor.com/blog/2015/06/23/new-oss-build-environment-and-xamarin-support https://www.appveyor.com/docs/installed-software#mingw-msys-cygwin).

I was more or less completely unaware of this, and haven't noticed any issues running "their" version of `diff` provided by default. Nevertheless, I'll be closing this issue for now - and leave it up to you to decide if future actions might eventually be taken on Appveyor integration.

Regards, NiteHawk

**Comment by bluebird75** [comment]
Maybe. Good news that this is fixed because that issue was annoying.

Can you submit a PR for a better appveyor.yml ? I'll be removing the on-site settings then and we can share it.

I also like your code coverage metrics. I remember looking for something similar one year ago but either it was not mature enough or I did not find it. Good to know that lua can be turned into a first citizen here.
